name: "Bug Report"
description: "Something is broken in WizardWebb"
title: "[BUG] <short summary>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough info for us to reproduce it.

  - type: input
    id: version
    attributes:
      label: Where are you running WizardWebb?
      placeholder: "Local Windows / Railway / Render / etc."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1) Go to ...
        2) Click ...
        3) See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Error Output
      placeholder: "Paste the error text or screenshot description."
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Python version + OS
      placeholder: "Python 3.x on Windows 11"
    validations:
      required: true
